bledevices/urls.py
from django.urls import path
from . import views

app_name = 'bledevices'
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('device/', views.BleDeviceListView.as_view(), name='all'),
    path('device/<int:pk>',views.BleDeviceDetailView.as_view(), name='bledevice_detail'),
    path('device/create/', views.BleDeviceCreateView.as_view(), name='bledevice_create'),
    path('device/<int:pk>/update/', views.BleDeviceUpdateView.as_view(), name='bledevice_update'),
    path('device/<int:pk>/delete/', views.BleDeviceDeleteView.as_view(), name='bledevice_delete'),
    path('device/<int:pk>/toggle/', views.BleDeviceToggleView.as_view(), name='bledevice_toggle'),
    path('network/', views.BleNetworkListView.as_view(), name='network_all'),
    path('network/<int:pk>',views.BleNetworkDetailView.as_view(), name='network_detail'),
    path('network/create/', views.BleNetworkCreateView.as_view(), name='network_create')
    #path('network/<int:pk>/delete/', views.BleNetworkDeleteView.as_view(), name='network_delete')
]

blenetwork/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bledevices/',include('bledevices.urls')),
    path('',include('portfolio.urls'))
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
    path('',views.HomeView.as_view(),name='home')
]

bledevices/models.py
from django.db import models
from django.core.validators import RegexValidator, MinLengthValidator
from django.utils import timezone
MAC_REGEX = "^([0-9A-F]{2}:){5}([0-9A-Fa-f]{2})|([0-9A-F]{4}\\.[0-9A-F]{4}\\.[0-9A-F]{4})$"

# Create your models here.
class BleDevice(models.Model):
    identifier = models.CharField(max_length=200,validators=[MinLengthValidator(5, "Identifier must be greater than 4 characters")])
    friendly_name = models.CharField(max_length=200,validators=[MinLengthValidator(2, "Friendly name must be greater than 1 character")])
    mac = models.CharField(max_length=17,validators=[RegexValidator(regex=MAC_REGEX,message="Expected format is AA:BB:CC:DD:EE:FF")])
    device_type = models.ForeignKey('BleDeviceType', on_delete=models.CASCADE, null=False)
    network = models.ForeignKey('BleNetwork', on_delete=models.CASCADE, null=False)
    active = models.BooleanField(null=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def toggle_active(self):
        self.active = not self.active
        self.save()
    
    def get_data(self):
        response=[]
        for data in self.data_set.all():
            datadict = {}
            if data.data_type.name == "TemperatureSensor":
                y_value = "Temperature"
            elif data.data_type.name == "HumiditySensor":
                y_value = "Humidity"
            datadict[self.friendly_name] = data.value
            datadict["time"] = data.created_at.strftime("%Y-%m-%d %H:%M:%S")
            response.append(datadict)
        
        return response

    def get_data_type(self):
        if self.device_type.name == "TemperatureSensor":
            return "Temperature"
        else:
            return "Humidity"
    def __str__(self):
        return self.identifier


class BleDeviceType(models.Model):
    name = models.CharField(max_length=50,validators=[MinLengthValidator(2, "Name must be greater than 1 character")])

    def __str__(self):
        return self.name

class Data(models.Model):
    value = models.FloatField()
    data_type = models.ForeignKey('BleDeviceType', on_delete=models.CASCADE, null=False)
    sensor = models.ForeignKey('BleDevice', on_delete=models.CASCADE, null=False)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{}Data({})".format(self.data_type.name, self.value)

class BleNetwork(models.Model):
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    active = models.BooleanField(null=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def toggle_active(self):
        self.active = not self.active
        for dev in self.bledevice_set.all():
            dev.active = self.active
            dev.save()
        self.save()
    
    def device_count(self):
        return self.bledevice_set.all().count()
    
    def is_fully_functional(self):
        if not self.active:
            return False
        for dev in self.bledevice_set.all():
            if dev.active == False:
                return False
        return True

    def __str__(self):
        return self.name

home/models.py
from django.db import models

# Create your models here.

bledevices/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView 
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic.base import TemplateView

from bledevices.models import BleDevice, BleDeviceType, BleNetwork

# Create your views here.
class BleDeviceListView(ListView):
    model = BleDevice

class BleDeviceDetailView(DetailView):
    model = BleDevice

class BleDeviceCreateView(CreateView):
    model = BleDevice
    fields = ['identifier', 'friendly_name', 'mac', 'device_type','network','active']
    success_url = reverse_lazy('bledevices:all')

class BleDeviceUpdateView(UpdateView):
    model = BleDevice
    fields = ['identifier', 'friendly_name', 'mac', 'device_type','network','active']
    success_url = reverse_lazy('bledevices:all')

@method_decorator(csrf_exempt, name='dispatch')
class BleDeviceToggleView(UpdateView):
    def post(self,request,pk):
        d = get_object_or_404(BleDevice,id=pk)
        print(d)
        d.toggle_active()
        return HttpResponse()
        

class BleDeviceDeleteView(DeleteView):
    model = BleDevice
    success_url = reverse_lazy('bledevices:all')


class BleDeviceTypeListView(ListView):
    model = BleDeviceType

class BleDeviceTypeDetailView(DetailView):
    model = BleDeviceType

class BleDeviceTypeCreateView(CreateView):
    model = BleDeviceType
    fields = '__all__'
class BleDeviceTypeUpdateView(UpdateView):
    model = BleDeviceType


class BleNetworkListView(ListView):
    model = BleNetwork

class BleNetworkCreateView(CreateView):
    model = BleNetwork
    fields = ['name', 'location', 'active']
    success_url = reverse_lazy('bledevices:home')

class BleNetworkDetailView(DetailView):
    model = BleNetwork

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in network devices list        
        context['connected_devices'] = list(kwargs.get('object').bledevice_set.all())
        return context

class HomeView(TemplateView):
    template_name = 'bledevices/home.html'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in devices data
        temp_dev_type = get_object_or_404(BleDeviceType,name='TemperatureSensor')
        temp_data = []
        temp_dev_names = []
        for dev in temp_dev_type.bledevice_set.all():
            temp_data = temp_data + dev.get_data()
            temp_dev_names.append(dev.friendly_name)
        hum_dev_type = get_object_or_404(BleDeviceType,name='HumiditySensor')
        hum_data = []
        hum_dev_names = []
        for dev in hum_dev_type.bledevice_set.all():
            hum_data = hum_data + dev.get_data()
            hum_dev_names.append(dev.friendly_name)
        
        context['temp_data'] = temp_data
        context['temp_dev_names'] = temp_dev_names
        context['hum_data'] = hum_data
        context['hum_dev_names'] = hum_dev_names
        context['dev_count'] = BleDevice.objects.all().count()
        context['network_count'] = BleNetwork.objects.all().count()
        context['inactive_dev_count'] = BleDevice.objects.filter(active=False).count()
        nff_networks = 0
        for network in BleNetwork.objects.all():
            if not network.is_fully_functional():
                nff_networks += 1
        context['not_fully_functional_network_count'] = nff_networks
        return context

home/views.py
from django.shortcuts import render

# Create your views here.

bledevices/templates/bledevices/bledevice_confirm_delete.html
{% extends "base_nav.html" %}
{% block main_page %}
<div class="d-flex flex-column align-items-center" style="width:100%;">
  <h1 class="mt-2">Delete BLE Device</h1>
    <p>Are you sure you want to delete the device: {{ bledevice }}?</p>
    <br>
    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" value="Yes, delete.">
    </form>
</div>
{% endblock %}

bledevices/templates/bledevices/bledevice_detail.html
{% extends "base_nav.html" %}
{% load humanize %}
{% load static %}
{% block head %}
{{ block.super }}
<style>
    .ChartShadow {
  -webkit-filter: drop-shadow(0px 20px 8px rgba(0, 0, 0, 0.2));
          filter: drop-shadow(0px 20px 8px rgba(0, 0, 0, 0.2));
    }
    .info-text {
        font-weight: 300;
        font-size: 1.1rem;
    }
    .info-title{
        font-weight: 500;
        font-size: 0.8rem;
    }
    .card .card-block, .card .card-body {
    padding: 30px 25px;
    }
</style>
<link rel="stylesheet" type="text/css" href="{% static 'bledevices/css/morris.css' %}">
{% endblock head %}
{% block main_page %}
<div class="container" style="flex-direction: column;">
<span style="float: right;">
<div class="mt-2">(Updated {{ bledevice.updated_at|naturaltime }})</div>
{% if bledevice.owner == user %}
<a href="{% url 'bledevices:bledevice_update' bledevice.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'bledevices:bledevice_delete' bledevice.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<br>
<h1 class="text-center mt-2">{{ bledevice.friendly_name }}</h1>

<div class="row">
    <!-- Device info -->
    <div class="col-xl-5 col-md-12">
        <div class="card h-100" style="margin-bottom: 30px;">
            <div class="card-header">
                <h5> Device info </h5>
            </div>
            <div class="card-block">
                <div class="row">
                    <div class="col">
                        <div class="row-12">
                                    <div class="col my-2">
                                        <a href="/bledevices/network/1" style="text-decoration:none;color:black;">
                                            <div class="row d-flex align-items-center">
                                                <div class="col-auto">
                                                    <i class="feather icon-user" style="font-size:30px;color:var(--bs-blue)"></i>
                                                </div>
                                                <div class="col">
                                                    <h3 class="info-text">{{bledevice.identifier}}</h3>
                                                    <span class="d-block text-uppercase info-title text-muted">DEVICE IDENTIFIER</span>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div class="col my-2">
                                        <div class="row d-flex align-items-center">
                                            <div class="col-auto">
                                                <i class="feather icon-help-circle" style="font-size:30px;color:var(--bs-blue)"></i>
                                            </div>
                                            <div class="col">
                                                <h3 class="info-text">{{bledevice.device_type}}</h3>
                                                <span class="d-block text-uppercase info-title text-muted">DEVICE TYPE</span>
                                            </div>
                                        </div>
                                    </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row-12">
                                    <div class="col my-2">
                                        <a href="/bledevices/network/1" style="text-decoration:none;color:black;">
                                            <div class="row d-flex align-items-center">
                                                <div class="col-auto">
                                                    <i class="feather icon-wifi" style="font-size:30px;color:var(--bs-blue)"></i>
                                                </div>
                                                <div class="col">
                                                    <h3 class="info-text">{{bledevice.network.name}}</h3>
                                                    <span class="d-block text-uppercase info-title text-muted">NETWORK NAME</span>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div class="col my-2">
                                        <a href="/bledevices/network/1" style="text-decoration:none;color:black;">
                                            <div class="row d-flex align-items-center">
                                                <div class="col-auto">
                                                    <i class="feather icon-server" style="font-size:30px;color:var(--bs-blue)"></i>
                                                </div>
                                                <div class="col">
                                                    <h3 class="info-text">{{bledevice.mac}}</h3>
                                                    <span class="d-block text-uppercase info-title text-muted">DEVICE MAC</span>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Device Measurements -->
    <div class="col-xl-6 mt-2 mt-xl-0">
        <div class="card h-100">
            <div class="card-header">
                <h5> Device measurements </h5>
            </div>
            <div class="card-block">
                <div class="text-center">
                    <h6> {{bledevice.get_data_type}} </h6>
                </div>
                <div id="morris-line-smooth-chart" class="ChartShadow" style="height:300px"></div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

{% block footer%}
<script src="{% static 'bledevices/js/raphael.min.js' %}"></script>
<script src="{% static 'bledevices/js/morris.min.js' %}"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    function toggle(url,pk) {
        $.post(url).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
        });
    }
</script>
<script>
    $(document).ready(function() {
        setTimeout(function() {
            Morris.Line({
            element: 'morris-line-smooth-chart',
            data: {{bledevice.get_data | safe}},
            xkey: 'time',
            redraw: true,
            resize: true,
            ykeys: ['{{bledevice.friendly_name}}'],
            hideHover: 'auto',
            responsive:true,
            labels: ['{{bledevice.friendly_name}}'],
            lineColors: ['#0d6efd', '#A389D4']
            });
        }, 700);
    });
</script>
{% endblock %}

bledevices/templates/bledevices/bledevice_form.html
{% extends "base_nav.html" %}
{% block main_page %}
{% load crispy_forms_tags %}
<div class="container d-flex flex-column">
<h1 class="text-center mt-2"> Add BLE Device</h1>
<div class="d-flex justify-content-center">
<form action="" method="post" id="upload_form" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Submit">
  <input type="submit" value="Cancel" onclick="window.location.href='{% url 'bledevices:all' %}';return false;">
</form>
</div>
</div>
{% endblock %}

bledevices/templates/bledevices/bledevice_list.html
{% extends "base_nav.html" %}
{% load humanize %}
{% block main_page %}
<h1 class="text-center mt-2">BLE Devices</h1>
{% if bledevice_list %}
<div class="row d-flex justify-content-center">
  {% for bledevice in bledevice_list %}
  <div class="col-md-6 col-lg-4 col-xl-3 py-2">
  <div {% if bledevice.active %} class = "card h-100 text-white bg-success mb-3" {% else %} class="card h-100 text-white bg-secondary mb-3" {% endif %}">
    <div class="card-header bg-transparent">{{bledevice.network.name}}</div>
    <div class="card-body">
      <h5 class="card-text text-center">{{ bledevice.friendly_name}}</h5>
      <p class="card-text"> <strong>Identifier</strong>: {{ bledevice.identifier }} <br>
        <strong>MAC</strong>: {{ bledevice.mac }} <br>
        <strong>Type</strong>: {{ bledevice.device_type }}</p>
        <a href="{% url 'bledevices:bledevice_detail' bledevice.id %}" class="btn btn-light">Detail</a>
        <a href="#" onclick="toggle.call(this,event,'{% url 'bledevices:bledevice_toggle' bledevice.id %}')" class="btn btn-light">Toggle</a>
        <a href="{% url 'bledevices:bledevice_delete' bledevice.id %}" class="btn btn-light">Remove</a>
    </div>
    <div class="card-footer">
      <small class="text-white">Last updated {{ bledevice.updated_at | naturaltime }}</small>
    </div>
  </div>
  </div>
  {% endfor %}
</div>
{% else %}
  <p class="text-center">There are no BLE devices in the database.</p>
{% endif %}
{% endblock main_page %}
{% block footer %}
<script>
  function toggle(event,url) {
    event.preventDefault();
    $.post(url, {},  function(rowz){
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
    parentCard = $(this).closest(".card");
    if (parentCard.hasClass("bg-secondary")){
      parentCard.removeClass("bg-secondary");
      parentCard.addClass("bg-success");
    }
    else{
      parentCard.removeClass("bg-success");
      parentCard.addClass("bg-secondary");
    }
}
</script>
{% endblock footer%}

bledevices/templates/bledevices/blenetwork_detail.html
{% extends "base_nav.html" %}
{% load humanize %}
{% block main_page %}
<span style="float: right;">
{% if blenetwork.owner == user %}
<a href="{% url 'bledevices:blenetwork_update' blenetwork.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'bledevices:blenetwork_delete' blenetwork.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1 class="text-center mt-2">{{ blenetwork.name }}</h1>
<p>
{% if connected_devices %}
<div class="container">
    <div class="row">
        {% for device in connected_devices %}
        <div class="col-md-6 col-lg-4 col-xl-3 py-2">
            <div {% if device.active %} class = "card h-100 text-white bg-success mb-3" {% else %} class="card h-100 text-white bg-secondary mb-3" {% endif %}">
                <div class="card-header bg-transparent">{{device.network.name}}</div>
                <div class="card-body">
                    <h5 class="card-text text-center">{{ device.friendly_name}}</h5>
                    <p class="card-text">   <strong>Identifier</strong>: {{ device.identifier }} <br>
                                            <strong>MAC</strong>: {{ device.mac }} <br>
                                            <strong>Type</strong>: {{ device.device_type }}</p>
                    <div class="text-center">
                        <a href="{% url 'bledevices:bledevice_detail' device.id %}" class="btn btn-light">Detail</a>
                        <a href="#" class="btn btn-light" onclick="toggle.call(this,event,'{% url 'bledevices:bledevice_toggle' device.id %}', {{ device.id }}); return false;"> Toggle </a>
                    </div>
                </div>
                <div class="card-footer">
                    <small class="text-white">Last updated {{ device.updated_at | naturaltime }}</small>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
    <p class="text-center">There are no BLE devices in this network.</p>
{% endif %}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    function toggle(event,url,pk) {
        $.post(url).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
        });
        card = $(this).closest('.card')
        if(card.hasClass('bg-success')){
            card.removeClass('bg-success');
            card.addClass('bg-secondary');
        }
        else{
            card.removeClass('bg-secondary');
            card.addClass('bg-success');
        }
    }
</script>
{% endblock %}

bledevices/templates/bledevices/blenetwork_form.html
{% extends "base_nav.html" %}
{% block main_page %}
{% load crispy_forms_tags %}
<div class="d-flex flex-column" style="width:100%;">
<h1 class="text-center mt-2"> Add BLE Network</h1>
<div class="d-flex justify-content-center">
<form action="" method="post" id="upload_form" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Submit">
  <input type="submit" value="Cancel" onclick="window.location.href='{% url 'bledevices:home' %}';return false;">
</form>
</div>
</div>
{% endblock %}

bledevices/templates/bledevices/blenetwork_list.html
{% extends "base_nav.html" %}
{% load humanize %}
{% block main_page %}
<div class="container" style="flex-direction: column;">
<h1 class="text-center mt-2">BLE Networks</h1>
{% if blenetwork_list %}
<div class="container">
  <div class="row d-flex justify-content-center">
    {% for blenetwork in blenetwork_list %}
    <div class="col-md-6 col-lg-4 col-xl-3 py-2">
    <div {% if not blenetwork.active %} class="card h-100 text-white bg-secondary mb-3" {% elif blenetwork.is_fully_functional %} class = "card h-100 text-white bg-success mb-3" {% else %} class = "card h-100 bg-warning mb-3" {% endif %}">
      <div class="card-body">
        <h5 class="card-text text-center">{{ blenetwork.name}}</h5>
        <p class="card-text"> 
          <strong>Location</strong>: {{ blenetwork.location }} <br>
          <strong>Devices</strong>: {{ blenetwork.device_count }}
          </p>
          <a href="{% url 'bledevices:network_detail' blenetwork.id %}" class="btn btn-light">Detail</a>
      </div>
      <div class="card-footer">
        <small {% if blenetwork.active and not blenetwork.is_fully_functional %}class="text-black"{% else %}class="text-white"{% endif %}>Last updated {{ blenetwork.updated_at | naturaltime }}</small>
      </div>
    </div>
    </div>
    {% endfor %}
  </div>
</div>
</div>
{% else %}
  <p>There are no BLE devices in the database.</p>
{% endif %}
</main>
{% endblock %}

bledevices/templates/bledevices/home.html
{% extends "base_nav.html" %}
{% load humanize %}
{% load static %}
{% block head %}
{{ block.super }}
<style>
    .ChartShadow {
  -webkit-filter: drop-shadow(0px 20px 8px rgba(0, 0, 0, 0.2));
          filter: drop-shadow(0px 20px 8px rgba(0, 0, 0, 0.2));
    }
    .card .card-block, .card .card-body {
    padding: 30px 25px;
    }
</style>
<link rel="stylesheet" type="text/css" href="{% static 'bledevices/css/morris.css' %}">
{% endblock head %}
{% block main_page %}
    <h1 class="text-center mt-2">BLE Home</h1>
    <!-- Presentation start-->
    <div class="row">
    <div class="col-xl-4 col-md-6">
        <div class="card" style="margin-bottom: 30px;">
            <div class="card-block border-bottom">
                <a href="{% url 'bledevices:all' %}" style="text-decoration:none;color:black;">
                    <div class="row d-flex align-items-center">
                        <div class="col-auto">
                            <i class="feather icon-cpu" style="font-size:30px;color:var(--bs-blue)"></i>
                        </div>
                        <div class="col">
                            <h3>{{dev_count}}</h3>
                            <span class="d-block text-uppercase text-muted">TOTAL DEVICES</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card-block border-bottom">
                <a href="{% url 'bledevices:network_all' %}" style="text-decoration:none;color:black;">
                    <div class="row d-flex align-items-center">
                        <div class="col-auto">
                            <i class="feather icon-wifi" style="font-size:30px;color:var(--bs-blue)"></i>
                        </div>
                        <div class="col">
                            <h3>{{network_count}}</h3>
                            <span class="d-block text-uppercase text-muted">TOTAL NETWORKS</span>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card-block">
                <a href="{% url 'bledevices:all' %}" style="text-decoration:none;color:black;">
                    <div class="row d-flex align-items-center">
                        <div class="col-auto">
                            <i class="feather icon-alert-circle" style="font-size:30px;color:var(--bs-red)"></i>
                        </div>
                        <div class="col">
                            <h3>{{inactive_dev_count}}</h3>
                            <span class="d-block text-uppercase text-muted">INACTIVE DEVICES</span>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="card">
            <div class="card-block border-bottom">
                <div class="row d-flex align-items-center">
                    <div class="col-auto">
                        <i class="feather icon-map-pin" style="font-size:30px;color:var(--bs-blue)"></i>
                    </div>
                    <div class="col">
                        <h3>{{network_count}}</h3>
                        <span class="d-block text-uppercase text-muted">LOCATIONS</span>
                    </div>
                </div>
            </div>
            <div class="card-block border-bottom">
                <a href="{% url 'bledevices:network_all' %}" style="text-decoration:none;color:black;">
                    <div class="row d-flex align-items-center">
                        <div class="col-auto">
                            <i class="feather icon-alert-triangle" style="font-size:30px;color:var(--bs-yellow)"></i>
                        </div>
                        <div class="col">
                            <h3>{{not_fully_functional_network_count}}</h3>
                            <span class="d-block text-uppercase text-muted">MALFUNCTIONING NETWORKS</span>
                        </div>
                    </div>
                </a>
            </div>
        </div>

    </div>
    <div class="col-xl-8 col-md-6">
        <div class="card">
            <div class="card-header">
                <h5>Devices Measurements</h5>
            </div>
            <h5 class="text-center"> Temperature </h5>
            <div class="card-block px-0 py-3">
                <div id="temp-chart" class="ChartShadow" style="height:300px"></div>
            </div>
            <h5 class="text-center"> Humidity </h5>
            <div class="card-block px-0 py-3">
                <div id="hum-chart" class="ChartShadow" style="height:300px"></div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block footer  %}
<script src="{% static 'bledevices/js/raphael.min.js' %}"></script>
<script src="{% static 'bledevices/js/morris.min.js' %}"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        setTimeout(function() {
            Morris.Line({
            element: 'temp-chart',
            data: {{temp_data | safe}},
            xkey: 'time',
            redraw: true,
            resize: true,
            ykeys: {{ temp_dev_names | safe }},
            hideHover: 'auto',
            responsive:true,
            labels: {{ temp_dev_names | safe }},
            xlabels: 'day',
            });
            Morris.Line({
            element: 'hum-chart',
            data: {{hum_data | safe}},
            xkey: 'time',
            redraw: true,
            resize: true,
            ykeys: {{ hum_dev_names | safe }},
            hideHover: 'auto',
            responsive:true,
            labels: {{ hum_dev_names | safe }},
            xlabels: 'day',
            });
        }, 700);
    });
</script>
{% endblock footer %}